version: '3.7'

services:
  frontend:
    container_name: portfolio
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/portfolio'
      - '/usr/src/portfolio/node_modules'
    ports:
      - 3000:3000