version: '3.7'

services:
  frontend:
    container_name: testportfolio
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/testportfolio'
      - '/usr/src/testportfolio/node_modules'
    ports:
      - 3001:3000